### ISSUE TITLE
Explain the Hamming distance/key separation concerns

### ISSUE THREAD

**Issue by KellerFuchs** [paragonie/ciphersweet#14]
docs/internals/01-key-hierarchy should explain why the Haming distance of the constants (rather than them being unequal) is relevant for key separation.

See #11

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/ciphersweet/commit/488fd48f89e61ef63984ffbd12105088c99734e5 -> https://github.com/paragonie/ciphersweet/blob/488fd48f89e61ef63984ffbd12105088c99734e5/docs/internals/01-key-hierarchy.md

**Comment by KellerFuchs** [comment]
Thanks, @paragonie-scott :)
