### ISSUE TITLE
How to do a string search?

### ISSUE THREAD

**Issue by OmegaZero** [paragonie/ciphersweet#20]
The documentation provides an example for how to do a search on the last four of the SSN, but how do you setup a string search?  For something like a last name where the length could be variable - an example would be nice to see.

Thanks!

**Comment by paragonie-scott** [comment]
Check the examples directory. We have complete examples there.

**Comment by OmegaZero** [comment]
Unless I'm looking in the wrong place the only example I can see if the SSN example I mentioned before...?

**Comment by OmegaZero** [comment]
Ah ok I misunderstood the potential (and wasn't sure how it was done to begin with - makes sense now :) )

I'll just limit it to searching on the first letter of the last name, thanks!

**Comment by paragonie-scott** [comment]
No problem at all. I'm going to tag this as a documentation issue since it could be made clearer.

**Comment by paragonie-scott** [comment]
I've updated the README to make this a bit clearer. Thanks for your feedback.  :)
