### ISSUE TITLE
Is a salt needed with Halite encryption?  How do I supply one?

### ISSUE THREAD

**Issue by OmegaZero** [paragonie/ciphersweet#21]
Is there a way to provide a salt value with the encryption for Halite?  Or do I even need to (perhaps the salt is included in the encrypted value)?  I see you can use a salt to derive a password but I don't see anything about doing symmetric encryption with a salt.

Thanks!

**Comment by OmegaZero** [comment]
Ah  yes, my apologies!  And thanks for the help again! :)

**Comment by paragonie-scott** [comment]
Happy to help :)
