### ISSUE TITLE
EncryptedField doesn't apply transforms unless it is used in EncryptedRow

### ISSUE THREAD

**Issue by rlittlefield** [paragonie/ciphersweet#22]
I noticed that while the EncryptedRow applies the transforms as it generates the blind indexes, the EncryptedField does not call this function. Calls to getBlindIndex will instead produce an index of the entire number.

I tested this by producing a python port (still in progress), which doesn't perform the "last four" part of the transform, but still gets the same blind index value in my version of this test:

https://github.com/paragonie/ciphersweet/blob/master/tests/EncryptedFieldTest.php#L253

**Comment by paragonie-scott** [comment]
Good catch. I must've refactored too much in an earlier version and removed the transformation processing.

`v1.4.0` does the correct thing.
