### ISSUE TITLE
Do we use ciphersweet's ciphertext in place of Halite?

### ISSUE THREAD

**Issue by OmegaZero** [paragonie/ciphersweet#25]
After reading the documentation it seems as though the ciphertext is encrypted text with the benefit of you having separate blind indexes. Can we just use Halite for storing the ciphertext and then use the blind indexes from ciphersweet for lookups?  Is there any benefit/drawbacks to doing this?

Thanks!

**Comment by paragonie-scott** [comment]
You could. Instead of `prepareForStorage()`, you can juts use `getAllBlindIndexes()` and call it a day.

The only drawback is that Halite doesn't aim to be compatible with anything except itself.

**Comment by OmegaZero** [comment]
Should I just use ciphersweet instead of Halite then?  Is Halite more secure?

**Comment by paragonie-scott** [comment]
The difference in security between each library is effectively zero, assuming `ModernCrypto` from CipherSweet.

Halite also includes asymmetric cryptography (Ed25519, X25519, etc.), CipherSweet is symmetric-only.

**Comment by OmegaZero** [comment]
Ok makes sense.  One more question: is FIPS 140-2 _less_ secure than ModernCrypto?

**Comment by paragonie-scott** [comment]
Generally speaking: FIPS 140-2 forces you to use less-secure asymmetric cryptography (RSA, ECC with unsafe curves, etc.).

FIPSCrypto does the best it can with the FIPS 140-2 approved algorithms and is secure, but I have less confidence in the security of any FIPS-compliant system than I would a system that's permitted to use Curve25519. Until they adjust their list of approved algorithms, this will continue to be the case.

**Comment by OmegaZero** [comment]
excellent.  Thank you so much, again!

**Comment by OmegaZero** [comment]
What about Halites use of HiddenString - I don't see anything similar in CipherSweet, is that a concern?

**Comment by paragonie-scott** [comment]
> What about Halites use of HiddenString - I don't see anything similar in CipherSweet, is that a concern?

Halite has a different, more general-purpose design philosophy.

CipherSweet is designed for use with databases, so the safety of HiddenString was eschewed in favor of simpler UX.

Key objects are used by CipherSweet instead of strings (see; `KeyProvider`), so there's no risk of losing your encryption keys to a stack trace.

> Also Can I use Halites EncryptionKey::generate(); to generate the key for ciphersweet?

They're wholly disparate projects, but use the same underlying RNG.

**Comment by OmegaZero** [comment]
Can I gain access to that hex encoded value that was generated by the key in halite to pass it to the StringProvider of ciphersweet though?  Like new StringProvider(new ModernCrypto(), KeyFactory::loadEncryptionKey($key))?

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/blob/master/doc/Classes/Key.md#getrawkeymaterial

**Comment by OmegaZero** [comment]
excellent, that worked. Is there any reason I _NEED_ to use a separate name for addBlindIndex? Like is it used for any type of internal salt?  Just wondering cause since I'm using Halite for the encryption (for now) and ciphersweet for the just wondering if I could make a generic function like below.  I guess in reality I'm just using CipherSweet for hashing, not entirely how it was intended to be used (but it works and somehow I feel more comfortable than me figuring out the right hashing security algo).

```
    public function getBlindIndex(string $plainText)
    {
        $key = $this->loadKey();

        $provider = new StringProvider(
            new ModernCrypto(),
            $key->getRawKeyMaterial()
        );
        $engine = new CipherSweet($provider);

        $index = (new EncryptedField($engine, 'fooTable', 'fooField'))
            ->addBlindIndex(
                new BlindIndex(
                    'fooIndexName',
                    [],
                    32
                )
            );

        return $index->getBlindIndex($plainText,'fooIndexName');
    }
```

honestly it's a lot for just a hash.  Too bad it's not something more like 

`$indexValue = $engine->getIndexValue($plainText,32);`

again though, I'm not really using it for how it's supposed to be used I guess.

**Comment by paragonie-scott** [comment]
> Is there any reason I NEED to use a separate name for addBlindIndex? Like is it used for any type of internal salt?

No. This was done to facilitate any number of possible database designs.

* You could have one massive `blind_index` table with `type`, `value`, `idnumber` as the columns.
* You could have an additional column in each row of each table, to accommodate each blind index.
* You could have a separate join table of blind indexes for various use cases.

No matter how your database is laid out, we wanted to work with it.

**Comment by paragonie-scott** [comment]
I'm going to close this issue. Please feel free to open a new one if you run into any bugs with our software.
