### ISSUE TITLE
EncryptedRow::getBlindIndex throws BlindIndexNotFoundException for non-compound indexes

### ISSUE THREAD

**Issue by dan-lambert** [paragonie/ciphersweet#37]
`EncryptedRow::getBlindIndex` is implemented as though `$this->blindIndexes` were an array of `BlindIndex` indexed by index name. It's actually an array of arrays (of `BlindIndex` indexed by index name) indexed by column name. When passed the name of a non-compound index it therefore fails to find it the index, and throws a `BlindIndexNotFoundException`.

**Comment by paragonie-scott** [comment]
Good catch! This is totally counterintuitive.

To avoid breaking BC, I'm going to have to add a method to `EncryptedRow` that behaves as you would expect.

Is `getBlindIndexForField()` a good name?

**Comment by paragonie-scott** [comment]
Nevermind, I misunderstood something fundamental. I'll get this fixed ASAP and included in the `v1.9.0` release.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/ciphersweet/commit/d2175e3025c1cfeb5729bc33d1d8d16d8e7e6bcd contains the fix. I'm going to review the entire class for other design warts that need removing.

**Comment by paragonie-scott** [comment]
`v1.9.0` is coming today.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/ciphersweet/releases/tag/v1.9.0 is now available. Thanks a ton for reporting this @dan-lambert! 👍

**Comment by dan-lambert** [comment]
Works a treat. Thanks so much @paragonie-scott!
