### ISSUE TITLE
[Documentation] Blind Index `type` Appears Unused

### ISSUE THREAD

**Issue by mcordingley** [paragonie/ciphersweet#38]
I'm assuming that the `type` value from a blind index is useful somehow, as [the docs tell me this is the case](https://github.com/paragonie/ciphersweet/tree/master/docs#encryptedfield), but nowhere is it defined what the type is used for or how. From reading through the source, I see how the value is calculated but again see nothing that actually uses it.

Can you please update the documentation with how this value is used?

**Comment by mcordingley** [comment]
It's looking like the idea is for there to be a single filters table and for this value to be used to look up values from that table, e.g.

```
CREATE TABLE filters (
    foreign_id UNSIGNED INTEGER NOT NULL,
    type VARCHAR(255) NOT NULL,
    value TEXT NOT NULL
);

SELECT foreign_id
FROM filters
WHERE type = 'akjl4'
  AND value = '4jkha'
```

**Comment by paragonie-scott** [comment]
> It's looking like the idea is for there to be a single filters table and for this value to be used to look up values from that table

The idea was to facilitate that design, if so desired. We strive to be vendor-agnostic with respect to database software.

**Comment by mcordingley** [comment]
Thanks. I will open other issues or PRs around making this a bit more user friendly.
