### ISSUE TITLE
Managing Coincidences

### ISSUE THREAD

**Issue by mcordingley** [paragonie/ciphersweet#43]
Suppose we are executing a query using a blind index and a query against the index returns multiple possible hits. How do we differentiate true positives from false positives? Decrypt and compare raw values?

**Comment by paragonie-scott** [comment]
> How do we differentiate true positives from false positives? Decrypt and compare raw values?

Yes. The blind index is meant to turn "decrypt and manually compare billions of rows" into "decrypt and manually compare dozens of rows".

**Comment by mcordingley** [comment]
OK. Wanted to make sure this was intended. Thanks.
