### ISSUE TITLE
Question: Is it possible to interact with the database using public / private keys

### ISSUE THREAD

**Issue by jcalfee** [paragonie/ciphersweet#46]
I need Bob to create a row for Alice using Alice's public key.  Alice would then of course search for that row using her private key.  Is it possible to use ECC cryptography with ciphersweet?

**Comment by paragonie-scott** [comment]
The focus of this library is searchable symmetric encryption.

You can hack asymmetric cryptography into it (i.e. `sodium_crypto_box_seal()`). An earlier design included this as a feature, but it seemed unwieldy from an API perspective. 

If you require custom development to support the asymmetric cryptography use cases, please email the CEO a request for a quote: `info at paragonie dot com`.

**Comment by jcalfee** [comment]
Thanks, I'll pass this info along.

**Comment by jcalfee** [comment]
I just found a write up under [the solution](https://paragonie.com/blog/2017/05/building-searchable-encrypted-databases-with-php-and-sql#solution) linked from your page.  The problem I see with this is that each blind index requires a distinct key but the only distinct key Bob has for Alice is publically known.  So, in the case above Alice's distinct key is her public key.  Key stretching is not strong enough to prevent an adversary from also analyzing the database to see if Alice got a message.  There are too many users to establish a shared secret pairs to use as the blind index key.  I believe that may be how you were going to use `sodium_crypto_box_seal` ..

Did you have an alternative in ind?
