### ISSUE TITLE
Documentation enhancement request (re: Blind Index Planning)

### ISSUE THREAD

**Issue by udf2457** [paragonie/ciphersweet#48]
Hi,

Re: The Blind Index Planning page of the docs (https://ciphersweet.paragonie.com/php/blind-index-planning)

It would be helpful for the non-cryptographers amongst us to perhaps provide a plain-english definition of what you mean by the terms `output size` and  `input domain`.

I have tried asking Mr Google what an index input domain is but he was not being particularly helpful.  Therefore whilst I think I know what you mean by the term, I would rather be "safe than sorry" and see a plain-english definition magically appear in the docs.  ;-)

Thanks and keep up the fabulous work !

**Comment by paragonie-scott** [comment]
https://ciphersweet.paragonie.com/php/blind-index-planning -- how does this look now?

**Comment by udf2457** [comment]
> https://ciphersweet.paragonie.com/php/blind-index-planning -- how does this look now?

A significant step in in the right direction.  If I were being picky, I might question the following:

1) Whether the expression _"existing index ("name_goes_here") has an output size of"_ perhaps needs to be tweaked ?  Since in essence you're talking about the (average) length of the plaintext before it gets encrypted, right ?

2) The hot-off-the-press definition for `Output size`, you say _"you want your blind index output to be"_.  But surely it's not necessarily a case of what "I" want ?  Since the purpose of `FieldIndexPlanner` is to give me the recommended range ?  Taking your example code, going by your definition, I'm saying _"I want the output to be 16"_  but then the output from `FieldIndexPlanner` is saying _"No, between 4 and 11"_.  (Maybe I'm overthinking this point though !)

**Comment by paragonie-scott** [comment]
> Since in essence you're talking about the (average) length of the plaintext before it gets encrypted, right ?

No, the output sizes of **other indexes built from the same input** diminish the safe boundary of your new index on the same input.

**Comment by udf2457** [comment]
Alright, let me have a another noob go at "getting" this whole `output size` thing....

Are you saying `output size` for `FieldIndexPlanner` is like `blake2b` and its "pick your own digest length" approach ?

**Comment by paragonie-scott** [comment]
I've updated the documentation once again: https://ciphersweet.paragonie.com/php/blind-index-planning

**Comment by paragonie-scott** [comment]
> Are you saying `output size` for `FieldIndexPlanner` is like `blake2b` and its "pick your own digest length" approach ?

Yes, your output size is something you get to choose. The planner tells you the minimum and maximum safe values (inclusive).

When you're adding an **existing** index, you have to provide the output size of each existing index. That will inform the planner of how much leakage is already present in the existing indexes, and therefore how much to limit the recommendations for an additional index on the same field.

**Comment by udf2457** [comment]
> I've updated the documentation once again: https://ciphersweet.paragonie.com/php/blind-index-planning

That's awesome !  Now it all clicks !  Turns out I was overthinking what needed too be done at the first stage, and also the whole thing about concatenations on the same data was sort of there in my mind but I couldn't see how the pieces fitted together to keep things safe, which I do now.

Thanks for your patience !

**Comment by paragonie-scott** [comment]
Happy to help! Thanks for your valuable feedback on improving our documentation. :)
