### ISSUE TITLE
EncryptedField does not convert non-string data types to/from string

### ISSUE THREAD

**Issue by bdewater** [paragonie/ciphersweet#50]
Hello and thank you for your work on CipherSweet! 

I'm currently working on a Ruby port and I noticed a difference between the `EncryptedRow` and `EncryptedField` classes: the former uses `convertToString` and `convertFromString` but the latter does not. This seems like an oversight (since it makes the implementations not interchangeable to use when using EncryptedRow used non-string types) but I wanted to check in here in case it was intentionally designed this way?

**Comment by paragonie-security** [comment]
If you need data type conversion, use `EncryptedRow` even if you only have one field.

The `EncryptedField` was a super early design and the concerns about non-string data types weren't in scope. We have no plans of adding this kind of support to `EncryptedField`; it simply exists as a minimalist interface for "I need to encrypt text but still use it in WHERE clauses in SELECT queries".

**Comment by bdewater** [comment]
Thanks!
