### ISSUE TITLE
Per user master key

### ISSUE THREAD

**Issue by lekoala** [paragonie/ciphersweet#59]
I don't know if this is the right place to ask, but I've been wondering if it would be possible to encrypt the data with a key per user.

Basically my idea would be this. By default, there is only one master key. That means that is it not possible to achieve zero knowledge encryption: as a platform owner, you have access to the master key.

What I'd like to do, is to be able to have a third party key provider that would provide a key per user. Therefore, the data is encrypted and only readable for that given user.

Now, here is my issue : i'd like to be able to have some kind of "sharing" mechanism, a bit like when you would do with a private/public keypair. The idea is to be able to implement something similar to this:
https://developer.virgilsecurity.com/docs/purekit/data-encryption/secure-data-sharing/

Let's say that third party service that provides a user key also serve as a sharing api. A given user (user A) can grant to another user (user B) access to a given set of ressource. Since ciphersweet use a key per table/field, it would be possible to grant to user B a decryption key derived from user A master key that would allow him to decrypt the data without being able to decrypt any other table/field that is not shared.

Also, an advantage of this third party key provider would be that if a user update his master key, we would be able to store any previous key and reencrypt the data. An old key could be then invalidated once all data has been reencrypted with the newer key.

Does that sounds reasonable/feasible @paragonie-staff ? From what I see from the codebase, it doesn't seem to crazy to try to do something like that.

**Comment by paragonie-security** [comment]
This is implemented in `v3.0.0`. https://github.com/paragonie/ciphersweet/releases/tag/v3.0.0

To support per-user keys, extend the [`MultiTenantProvider`](https://github.com/paragonie/ciphersweet/blob/master/src/KeyProvider/MultiTenantProvider.php) class.

* `getTenant()` selects a `KeyProvider` based on a given tenant.
* `getTenantFromRow()` gets the tenant ID (array key) based on the data stored in an encrypted row.
* `injectTenantMetadata()` injects some breadcrumb for `getTenantFromRow()` to use to select the appropriate key.

These methods were designed to be generalizable: If you implement AWS KMS support, for example, you'd probably store an encrypted data key with `injectTenantMetadata()` and then ask KMS to decrypt it in `getTenantFromRow()` (unless it's cached).

However you want to implement the business logic here is entirely up to you.
