### ISSUE TITLE
global blind index implementation?

### ISSUE THREAD

**Issue by slushpuppy** [paragonie/ciphersweet#65]
Hi,
       I am making a global search system from my app that allows users to search for encrypted data from multiple tables with differing schemas containing encrypted data. The only commonality between the data being searched are that they are all text searches with the same transformations. what would be the best way to go about doing this?

**Comment by paragonie-security** [comment]
Use `EncryptedMultiRows`, define a pseudo-table that all of the blind indexes would be defined over regardless of their actual location within the table.
