### ISSUE TITLE
sodium_crypto_pwhash() warns "empty password"

### ISSUE THREAD

**Issue by thisispiers** [paragonie/ciphersweet#73]
sodium_crypto_pwhash() warns "empty password" when the value for a blind index is an empty string or null.

My current workaround is to add this line to the beginning of BoringCrypto::blindIndexSlow()

`if ($plaintext === '') { $plaintext = ' '; }`

A unique value from a constant might be preferable.

**Comment by paragonie-security** [comment]
Fixed in `v4.0.1`
