### ISSUE TITLE
Use #[\SensitiveParameter]

### ISSUE THREAD

**Issue by thisispiers** [paragonie/ciphersweet#74]
PHP 8.2 is due to be released in November. Are plans in place to support this new feature?

**Comment by paragonie-security** [comment]
No _current_ plans, but we aren't ruling anything out. What did you have in mind?

**Comment by TimWolla** [comment]
I'm the author of [that RFC](https://wiki.php.net/rfc/redact_parameters_in_back_traces), I don't use this library.

> What did you have in mind?

The attribute should be applied to all parameters that hold sensitive data. For the PHP standard library this includes key material and plaintext data.

see paragonie/constant_time_encoding#48 where I made the necessary changes.

Looking at ciphersweet anything you run through `Util::memzero()` during destruction should likely receive the attribute, for `Util::aes256ctr()` all parameters except possibly the `$nonce` should receive the attribute, &c.

**Comment by paragonie-security** [comment]
Done in #76
