### ISSUE TITLE
Encryption/decryption speed

### ISSUE THREAD

**Issue by lekoala** [paragonie/ciphersweet#79]
Hi,

I'm currently working with large import/export of data. Basically, the flow is like this:
- check if the record exist using a blind index
- create or update the record (and encrypting the content, of course)

The issue is that doing so is really slow compared to plain queries/inserts in the php loop.

Is there any way to make this faster ? Having blind indexes is great, but if it's not possible to process records in bulk in a reasonable time frame, it defeats the purpose in some cases.

**Comment by paragonie-security** [comment]
Check how you're defining your blind index classes.

https://github.com/paragonie/ciphersweet/blob/a71508cad281ffcff31776e4c36f9613e87e764f/src/BlindIndex.php#L39

If you don't enable fast hashes, you get PBKDF2 or Argon2 by default.

**Comment by lekoala** [comment]
@paragonie-security i will give this a try! I somehow missed that from the documentation

**Comment by lekoala** [comment]
yes that works great. now i just need to rewrite all my blind indexes^^

**Comment by paragonie-security** [comment]
I'll make a note to update the documentation to make this more obvious.

The intent was security by default, which is important when working with low-entropy inputs.
