### ISSUE TITLE
permit Empty

### ISSUE THREAD

**Issue by aryala7** [paragonie/ciphersweet#83]
hey guys,
is there any way to set the permitEmpty attribute in the EncryptedRow.php? 
<img width="766" alt="Screenshot 2023-03-04 at 10 11 06 PM" src="https://user-images.githubusercontent.com/56627259/222923275-8ea51807-2ac9-418f-a98e-e869fce465fa.png">
because i couldn't find how to set this attribute to true. the problem i have encountered is that our project uses Graphql for the api section, and if i dont select all the encrypted columns it gives me a ``` Field is not defined in row ``` exception.

i can submit a PR and add parameter to the constructor if it will fix this issue

**Comment by paragonie-security** [comment]
https://github.com/paragonie/ciphersweet/blob/7459af64c412453ffa8813518c44292a9742c326/src/EncryptedRow.php#L824-L832

Call `setPermitEmpty(true)` on the `EncryptedRow` object.
