### ISSUE TITLE
Error in >=4.3.0 when setPermitEmpty option is used.

### ISSUE THREAD

**Issue by stevenmaguire** [paragonie/ciphersweet#93]
Version 4.3.0 introduced some new logic using the `is_scalar` method. It appears the new logic is meant to enforce some constraints on the value. Unfortunately, when the `setPermitEmpty` functionality it is possible for the value of `$row[$field]` to be null. Because `is_scalar(null)` evaluates to false, this new logic is being engaged when perhaps it shouldn't be.

https://github.com/paragonie/ciphersweet/blob/ccb2e1d36652bb0a2471c80a747626b9502f376f/src/EncryptedRow.php#L532-L534

<img width="396" alt="CleanShot 2023-08-09 at 12 45 32@2x" src="https://github.com/paragonie/ciphersweet/assets/1851973/6972e30c-c63c-4434-9c10-3d33543e91f9">

Perhaps this was an oversight?

**Comment by paragonie-security** [comment]
Check v4.5.0 which fixed this error.

**Comment by stevenmaguire** [comment]
I had read that version 4.5.0 addressed this issue, however it was still present when targeting that specific version. When digging deeper, it appears that the issue was ultimately coming from a framework specific behavior that changed the incoming fields in the encrypted row, which was then triggering this error. Thanks for following up.

**Comment by yormy** [comment]
I too can confirm that this is still an issue in 4.5.0

According to php docs:
`is_scalar() does not consider NULL to be scalar.`

**Comment by paragonie-security** [comment]
> According to php docs: `is_scalar() does not consider NULL to be scalar.`

This is a red herring.

https://github.com/paragonie/ciphersweet/blob/master/src/EncryptedRow.php#L613-L631

Look again:

https://github.com/paragonie/ciphersweet/blob/master/src/EncryptedRow.php#L613-L618

You need to declare your types optional. This is a new feature. See #92

**Comment by paragonie-security** [comment]
I've released `v4.5.1` which adds a more helpful exception message when NULL is encountered but the support for NULL is not declared in configuration.
